### PR TITLE
Productionize the project

### PR DESCRIPTION
**Pull request by cortinico**
Time to productionize the `detekt-compiler-plugin` 🚀 

I'm pushing a set of commits that takes care of bumping dependencies and make the overall process of bumping detekt/releasing easier.

Specifically I've bumped:
- Detekt to 1.17.1
- Kotlin to 1.4.32
- Gradle to 7.0.2
- Spek to 2.0.15
- AssertJ to 3.19.0
- Shadow to 7.0.0

Specifically, the project was currently not working as some of the dependencies are referencing a custom bintray repo. I'd say we can move this project to publish via Gradle Plugin portal only, keep the `0.x` numbering till we feel confident enough that we can call it a stable release. Therefore I've removed the Bintray publishing setup.

I've also updated the project to be a composite build, as we had to rely on Maven Local to test the Gradle plugin otherwise.

The Diff is quite big, but it can be reviewed commit by commit.
I would like to publish `0.4.0` to Gradle Portal just after this PR.

### CODE REVIEW

**Comment by chao2zhang** [comment]
> I've also updated the project to be a composite build, as we had to rely on Maven Local to test the Gradle plugin otherwise

Today I learned that composite build can save us from relying on Maven Local. Do you know if this is a common strategy that people use?

**Comment by chao2zhang** [comment]
I ended up reading a blog post as well as a 10-page Gradle documentation. LGTM!

**Comment by cortinico** [comment]
Great :) Are we fine merging this?

**Review by chao2zhang — APPROVED** [review]

**Comment by 3flex** [comment]
Just saw this. Just a heads up that we did have composite build setup for the detekt Gradle plugin for a whlie (I support this setup as well and introduced it initially in the main detekt project) but it was rolled back with https://github.com/detekt/detekt/pull/2493.

My preference would be for both this and the primary project's Gradle plugin to be setup as composite builds in the detekt project.

**Comment by cortinico** [comment]
> My preference would be for both this and the primary project's Gradle plugin to be setup as composite builds in the detekt project.

Agree.

Also we have this discussion to bring the topic again up to life: https://github.com/detekt/detekt/discussions/4052

**Pull request merged**
